spring.application.name=spring

security.jwt.secret=F868C47C-663C-4D71-AFB9-3FB52EFEE393
security.jwt.expiration-hours=3

spring.datasource.url=jdbc:postgresql://localhost:5432/airmanagement
spring.datasource.username=kaan
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect